"""GPU GFP-masking example on a public S3 multiscale OME-Zarr.

Reads a SmartSPIM/HCR fused volume from S3 at a chosen multiscale level, runs the
``gfp-mask`` model (a cupy/cuCIM masking routine driven by the inference pipeline),
and writes a ``uint8`` mask back to S3 as an OME-Zarr that mirrors the source pyramid.

The segmented level **L is parsed from the trailing level digit of ``--in-path``**
(e.g. ``.../fused.zarr/5`` -> L=5). The mask is written at that same level index, and
the coarser levels the source has below L (``L+1 .. N``) are regenerated by
downsampling the mask with the ``max`` (any-positive) reducer, which keeps every level
a strict binary mask. The output's OME-NGFF metadata copies the source datasets
``L..N`` verbatim (same paths and scales), so the mask overlays the original.

Requirements
------------
- A CUDA GPU with the post-processing stack installed:
  ``pip install -e ".[postprocess]"`` (``cupy-cuda12x`` + ``cucim-cu12``). The
  ``gfp-mask`` model is GPU-only.
- AWS credentials with write access to the output bucket. The input bucket
  ``aind-open-data`` is public (region ``us-west-2``); reading uses the standard AWS
  credential chain. If your environment has no credentials and signed S3 reads fail,
  TensorStore's s3 driver may need anonymous access configured.
- Run from the ``examples/`` directory (or with it on ``PYTHONPATH``) so
  ``example_utils`` is importable.

Usage
-----
python examples/run_gfp_mask_example.py \
    --in-spec in_spec.json \
    --out-bucket my-output-bucket \
    --out-prefix predictions/HCR_831990 \
    --devices cuda:0

``--in-spec`` is a TensorStore JSON spec (file path, raw JSON, or dict); the level L is
read from the trailing digit of its kvstore path. Omitting ``--in-spec`` uses a built-in
default pointing at::

    s3://aind-open-data/HCR_831990-s2-ls1_..._01-32-11/fusion/ch_488/fused.zarr/5

(level 5). Mask parameters can be customized via ``--params-json`` (see
``GfpMaskModel.from_json``); omit it to use defaults.
"""

import argparse
import asyncio
import json
import logging
import re
import sys
from typing import List, Optional, Tuple
from urllib.parse import urlparse

import boto3
import tensorstore as ts

from aind_torch_utils.config import InferenceConfig
from aind_torch_utils.run import load_model, run
from aind_torch_utils.utils import open_ts_spec
from example_utils.utils import load_json

# Default input spec (sample at multiscale level 5) used when --in-spec is omitted.
DEFAULT_IN_SPEC = {
    "driver": "zarr",
    "kvstore": {
        "driver": "s3",
        "bucket": "aind-open-data",
        "path": (
            "HCR_831990-s2-ls1_2026-05-15_00-00-00_processed_2026-05-19_01-32-11"
            "/fusion/ch_488/fused.zarr/5/"
        ),
        "aws_region": "us-west-2",
    },
}
DOWNSAMPLE_METHOD = "max"  # keeps coarser mask levels strictly binary
MAX_INFLIGHT = 8  # concurrent downsample chunks (peak RAM ~ MAX_INFLIGHT x chunk)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


def _open_or_create_s3_mask_zarr(
    bucket: str, path: str, shape, chunks, region: str
) -> ts.TensorStore:
    """Open (or create) a uint8 zarr2 array for the output mask on S3."""
    spec = {
        "driver": "zarr",
        "kvstore": {
            "driver": "s3",
            "bucket": bucket,
            "path": path,
            "aws_region": region,
        },
        "metadata": {
            "shape": list(shape),
            "chunks": list(chunks),
            "dtype": "|u1",  # uint8 mask
            "dimension_separator": "/",
        },
        "create": True,
        "delete_existing": True,
    }
    return ts.open(spec).result()


def _load_spec_dict(spec) -> dict:
    """Return a spec as a dict, mirroring open_ts_spec's input handling.

    Accepts a dict, a raw JSON string, or a path to a JSON file.
    """
    if isinstance(spec, str):
        stripped = spec.lstrip()
        if stripped.startswith("{") or stripped.startswith("["):
            return json.loads(stripped)
        with open(spec, "r", encoding="utf-8") as f:
            return json.load(f)
    return spec


def _kvstore_bucket_path(spec_dict: dict) -> Tuple[str, str, Optional[str]]:
    """Extract (bucket, path, aws_region) from a spec's kvstore.

    Handles both the dict form ({"driver": "s3", "bucket": ..., "path": ...}) and the
    shorthand string form ("s3://bucket/key").
    """
    kv = spec_dict.get("kvstore", spec_dict)
    if isinstance(kv, str):
        parsed = urlparse(kv)
        return parsed.netloc, parsed.path.lstrip("/"), None
    return kv.get("bucket", ""), kv.get("path", "").strip("/"), kv.get("aws_region")


def _scale_zyx(ds: dict) -> Optional[List[float]]:
    """Return the ZYX scale of a multiscales dataset entry, or None."""
    for ct in ds.get("coordinateTransformations", []):
        if ct.get("type") == "scale":
            return list(ct["scale"][-3:])
    return None


def _read_source_multiscales(
    bucket: str, group_path: str
) -> Optional[Tuple[dict, list, Optional[dict]]]:
    """Read the source OME-Zarr group's first multiscales block.

    Returns ``(multiscale_dict, datasets, omero)`` or ``None`` if the group has no
    multiscales metadata. Handles zarr v3 (``zarr.json``) and v2 (``.zattrs``).
    """
    group_uri = f"s3://{bucket}/{group_path}"
    attrs = None
    for fname in ("zarr.json", ".zattrs"):
        try:
            attrs = load_json(group_uri, fname)
            logger.info("Read OME metadata from %s/%s", group_uri, fname)
            break
        except Exception:
            continue
    if attrs is None:
        logger.warning("No zarr.json/.zattrs found at %s", group_uri)
        return None

    # zarr v3 nests user attributes under "attributes"; OME under "ome".
    attrs = attrs.get("attributes", attrs)
    ome = attrs.get("ome", attrs)
    multiscales = ome.get("multiscales", [])
    if not multiscales:
        return None
    ms = multiscales[0]
    return ms, ms.get("datasets", []), ome.get("omero")


def _build_mask_pyramid(
    bucket: str,
    base_path: str,
    datasets_from_l: list,
    region: str,
    chunk: int = 128,
) -> None:
    """Generate coarser mask levels by downsampling the segmented level.

    ``datasets_from_l`` is the source multiscales datasets sliced from level L
    onward; index 0 is the already-written segmented level. Each subsequent level is
    produced from the previous one with TensorStore's ``max`` downsample reducer and
    written as ``uint8`` at the source's original ``path`` string.
    """

    def _factors(prev_ds: dict, ds: dict) -> List[int]:
        s_prev, s_cur = _scale_zyx(prev_ds), _scale_zyx(ds)
        if s_prev is None or s_cur is None:
            raise ValueError("Source datasets are missing scale transforms.")
        return [max(1, round(s_cur[a] / s_prev[a])) for a in range(3)]

    async def _build_levels():
        sem = asyncio.Semaphore(MAX_INFLIGHT)
        ctx = ts.Context({"data_copy_concurrency": {"limit": 4}})

        for i in range(1, len(datasets_from_l)):
            prev_ds, ds = datasets_from_l[i - 1], datasets_from_l[i]
            sf_padded = [1, 1] + _factors(prev_ds, ds)

            downsampled = await ts.open(
                {
                    "driver": "downsample",
                    "downsample_factors": sf_padded,
                    "downsample_method": DOWNSAMPLE_METHOD,
                    "base": {
                        "driver": "zarr",
                        "kvstore": {
                            "driver": "s3",
                            "bucket": bucket,
                            "path": f"{base_path}{prev_ds['path']}/",
                            "aws_region": region,
                        },
                    },
                },
                context=ctx,
            )
            new_shape = list(downsampled.shape)
            nz, ny, nx = new_shape[2], new_shape[3], new_shape[4]
            cz, cy, cx = min(chunk, nz), min(chunk, ny), min(chunk, nx)

            output = await ts.open(
                {
                    "driver": "zarr",
                    "kvstore": {
                        "driver": "s3",
                        "bucket": bucket,
                        "path": f"{base_path}{ds['path']}/",
                        "aws_region": region,
                    },
                    "metadata": {
                        "shape": new_shape,
                        "chunks": [1, 1, cz, cy, cx],
                        "dtype": "|u1",
                        "dimension_separator": "/",
                    },
                    "create": True,
                    "delete_existing": True,
                },
                context=ctx,
            )

            async def _copy(z0, z1, y0, y1, x0, x1):
                async with sem:
                    data = await downsampled[:, :, z0:z1, y0:y1, x0:x1].read()
                    await output[:, :, z0:z1, y0:y1, x0:x1].write(data)
                    del data

            ranges = [
                (z0, min(z0 + cz, nz), y0, min(y0 + cy, ny), x0, min(x0 + cx, nx))
                for z0 in range(0, nz, cz)
                for y0 in range(0, ny, cy)
                for x0 in range(0, nx, cx)
            ]
            for j in range(0, len(ranges), 64):
                end = j + 64
                await asyncio.gather(*[_copy(*r) for r in ranges[j:end]])
            logger.info("[pyramid] wrote level %s shape=%s", ds["path"], new_shape)

    asyncio.run(_build_levels())


def _write_output_zattrs(
    bucket: str,
    base_path: str,
    source_ms: dict,
    datasets_from_l: list,
    omero: Optional[dict],
    region: str,
) -> None:
    """Write OME-NGFF .zattrs mirroring the source levels L..N.

    Copies the source multiscales block, replacing its datasets with ``datasets_from_l``
    verbatim (original paths + absolute scales), so the mask aligns spatially with the
    source. Output is written as zarr v2 ``.zattrs`` even when the source was v3.
    """
    ms = dict(source_ms)
    ms["datasets"] = datasets_from_l
    zattrs = {"multiscales": [ms]}
    if omero is not None:
        zattrs["omero"] = omero
    key = f"{base_path}.zattrs"
    boto3.client("s3", region_name=region).put_object(
        Bucket=bucket, Key=key, Body=json.dumps(zattrs).encode()
    )
    logger.info("Wrote OME-NGFF metadata to s3://%s/%s", bucket, key)


def _parse_args(argv: List[str]) -> argparse.Namespace:
    """Parse command-line arguments."""
    ap = argparse.ArgumentParser(
        description="Run the gfp-mask model on an S3 multiscale OME-Zarr."
    )
    ap.add_argument(
        "--in-spec",
        default=None,
        help=(
            "TensorStore JSON spec (file path or raw JSON). The level to segment is "
            "the trailing digit of its kvstore path. Defaults to the built-in sample "
            "(.../fused.zarr/5)."
        ),
    )
    ap.add_argument("--out-bucket", required=True)
    ap.add_argument(
        "--out-prefix",
        required=True,
        help="Output written to s3://<out-bucket>/<out-prefix>/gfp_mask.zarr/",
    )
    ap.add_argument("--aws-region", default="us-west-2")
    ap.add_argument("--devices", nargs="+", default=["cuda:0"])
    ap.add_argument("--patch", type=int, nargs=3, default=(64, 64, 64))
    ap.add_argument("--block", type=int, nargs=3, default=(256, 256, 256))
    ap.add_argument("--overlap", type=int, default=10)
    ap.add_argument("--batch", type=int, default=8)
    ap.add_argument(
        "--params-json",
        default=None,
        help="Optional JSON file of GfpMaskModel parameters.",
    )
    ap.add_argument("--prep-workers", type=int, default=2)
    ap.add_argument("--writer-workers", type=int, default=2)
    ap.add_argument(
        "--no-pyramid",
        action="store_true",
        help="Write only the segmented level (no coarser levels, no OME metadata).",
    )
    return ap.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> None:
    """Segment the level encoded in --in-spec and write a matching OME-Zarr pyramid."""
    args = _parse_args(sys.argv[1:] if argv is None else argv)

    # Input spec: explicit --in-spec, else the built-in sample.
    spec = args.in_spec if args.in_spec is not None else DEFAULT_IN_SPEC
    in_bucket, in_kv_path, _ = _kvstore_bucket_path(_load_spec_dict(spec))

    # Level L is the trailing digit of the kvstore path; the group is the path above it.
    in_kv_path = in_kv_path.rstrip("/")
    m = re.search(r"/(\d+)$", in_kv_path)
    if m is None:
        raise ValueError(
            f"The input spec's kvstore path must end with a multiscale level, e.g. "
            f".../fused.zarr/5; got '{in_kv_path}'"
        )
    level = m.group(1)  # keep as the source's path string (e.g. "5")
    group_path = in_kv_path[: m.start()]

    # --- Input store (existing zarr; metadata read from the store) ---
    logger.info("Opening input: s3://%s/%s (level %s)", in_bucket, in_kv_path, level)
    input_store = open_ts_spec(spec)
    shape = tuple(input_store.domain.shape)
    logger.info("Input shape=%s dtype=%s", shape, input_store.dtype)
    if len(shape) != 5:
        raise ValueError(
            f"Expected a 5D (T, C, Z, Y, X) input store, got shape {shape}."
        )
    z, y, x = shape[2:]

    # --- Source multiscales metadata (for pyramid + OME output) ---
    source_ms = datasets = omero = None
    datasets_from_l: list = []
    if not args.no_pyramid:
        ms_info = _read_source_multiscales(in_bucket, group_path)
        if ms_info is None:
            raise ValueError(
                "No OME multiscales metadata found on the source group; rerun with "
                "--no-pyramid to write only the segmented level."
            )
        source_ms, datasets, omero = ms_info
        paths = [d.get("path") for d in datasets]
        if level not in paths:
            raise ValueError(f"Level '{level}' not among source datasets {paths}.")
        start = paths.index(level)
        datasets_from_l = datasets[start:]

    # Clamp patch/block to the (possibly small) downsampled volume.
    patch = tuple(min(p, d) for p, d in zip(args.patch, (z, y, x)))
    block = tuple(min(b, d) for b, d in zip(args.block, (z, y, x)))
    if patch != tuple(args.patch) or block != tuple(args.block):
        logger.info(
            "Clamped to (Z,Y,X)=(%d,%d,%d): patch=%s block=%s", z, y, x, patch, block
        )

    # --- Output: segmented level written at the source's level index ---
    base_path = f"{args.out_prefix.rstrip('/')}/gfp_mask.zarr/"
    seg_path = f"{base_path}{level}/"
    chunks = (1, 1, min(128, z), min(128, y), min(128, x))
    logger.info("Creating segmented level: s3://%s/%s", args.out_bucket, seg_path)
    output_store = _open_or_create_s3_mask_zarr(
        args.out_bucket, seg_path, (1, 1, z, y, x), chunks, args.aws_region
    )

    # --- Model + config ---
    model = load_model("gfp-mask", args.params_json)
    cfg = InferenceConfig(
        patch=patch,
        block=block,
        overlap=args.overlap,
        batch_size=args.batch,
        devices=args.devices,
        amp=False,  # no torch math in the model; avoid a pointless float16 copy
        use_compile=False,  # torch.compile cannot trace the cupy/cuCIM region
        normalize="percentile",  # feed ~[0,1]; matches intensity_percentiles=(0,1)
        output_denormalize=False,  # mask is not in intensity space
        seam_mode="trim",
    )
    logger.info("Inference config:\n%s", cfg)

    run(
        model,
        input_store,
        output_store,
        cfg,
        num_prep_workers=max(1, args.prep_workers),
        num_writer_workers=max(1, args.writer_workers),
    )

    if args.no_pyramid:
        logger.info(
            "Done (single level %s). Skipped pyramid + OME metadata (--no-pyramid).",
            level,
        )
        return

    # --- Coarser levels L+1..N + OME-NGFF metadata mirroring the source ---
    _build_mask_pyramid(args.out_bucket, base_path, datasets_from_l, args.aws_region)
    _write_output_zattrs(
        args.out_bucket, base_path, source_ms, datasets_from_l, omero, args.aws_region
    )
    logger.info("Done. OME-Zarr mask written to s3://%s/%s", args.out_bucket, base_path)


if __name__ == "__main__":
    main()
