"""GPU GFP-masking example on a public S3 multiscale OME-Zarr.

Reads a SmartSPIM/HCR fused volume from S3 at a chosen multiscale level, runs the
``gfp-mask`` model (a cupy/cuCIM masking routine driven by the inference pipeline),
and writes a ``uint8`` mask back to S3 as an OME-Zarr that mirrors the source pyramid.

The segmented level **L is parsed from the trailing level digit of ``--in-path``**
(e.g. ``.../fused.zarr/5`` -> L=5). The mask is written at that same level index, and
the coarser levels the source has below L (``L+1 .. N``) are regenerated by
downsampling the mask with the ``max`` (any-positive) reducer, which keeps every level
a strict binary mask. The output's OME-NGFF metadata copies the source datasets
``L..N`` verbatim (same paths and scales), so the mask overlays the original.

Requirements
------------
- A CUDA GPU with the post-processing stack installed:
  ``pip install -e ".[postprocess]"`` (``cupy-cuda12x`` + ``cucim-cu12``). The
  ``gfp-mask`` model is GPU-only.
- AWS credentials with write access to the output bucket. The input bucket
  ``aind-open-data`` is public (region ``us-west-2``); reading uses the standard AWS
  credential chain. If your environment has no credentials and signed S3 reads fail,
  TensorStore's s3 driver may need anonymous access configured.
- Run from the ``examples/`` directory (or with it on ``PYTHONPATH``) so
  ``example_utils`` is importable.

Usage
-----
python examples/run_gfp_mask_example.py \
    --in-spec in_spec.json \
    --out-bucket my-output-bucket \
    --out-prefix predictions/HCR_831990 \
    --devices cuda:0

``--in-spec`` is a TensorStore JSON spec (file path, raw JSON, or dict); the level L is
read from the trailing digit of its kvstore path. Omitting ``--in-spec`` uses a built-in
default pointing at::

    s3://aind-open-data/HCR_831990-s2-ls1_..._01-32-11/fusion/ch_488/fused.zarr/5

(level 5). Mask parameters can be customized via ``--params-json`` (see
``GfpMaskModel.from_json``); omit it to use defaults. That same JSON may also carry
pipeline-normalization keys ``normalize``/``norm_lower``/``norm_upper`` — set
``"normalize": "global"`` with the dataset's global min/max to skip the per-block
percentile computation that bottlenecks prep, e.g.::

    {"normalize": "global", "norm_lower": 90.0, "norm_upper": 1200.0,
     "threshold": 0.1, "smooth_sigma": [0.5, 1, 1], "open_iterations": 1}

``threshold`` is in normalized ``[0, 1]`` (raw-intensity equivalent is
``norm_lower + threshold*(norm_upper - norm_lower)``); lower => more oversegmentation.
``open_iterations`` is a binary opening that removes tiny dots after thresholding
(``0`` disables it; raise ``threshold`` and/or ``open_iterations`` to despeckle more).

To fix chunk-to-chunk segmentation differences caused by source intensity
inhomogeneity (light-sheet shading / fusion seams), enable white top-hat flat-field
correction. A global background is estimated once from a coarse pyramid level and
subtracted before normalization, so a single global threshold segments uniformly
(seam-free). Add, e.g.::

    {"normalize": "global", "norm_lower": 90.0, "norm_upper": 1200.0,
     "threshold": 0.05, "smooth_sigma": [0.5, 1, 1], "open_iterations": 1,
     "flatfield": true, "flatfield_level": 8, "flatfield_opening_radius": 2,
     "flatfield_sigma": 1.0}

With ``flatfield`` on, ``threshold`` applies to the *flattened* signal and must be
re-tuned (subtraction compresses the dynamic range, so start lower). ``flatfield_level``
is the coarse level the background is estimated from; ``flatfield_opening_radius``
(coarse voxels) strips sparse cells from the estimate; ``flatfield_mode`` may be
``"subtract"`` (default, white top-hat) or ``"divide"`` (multiplicative shading).

If a fused volume has empty (zero) regions, the background estimate's grey-opening
reaches across the empty/tissue interface into the zeros and under-estimates the
background on the tissue side, so ``subtract`` leaves a bright false-positive rim
*at the tissue boundary* (not the volume edge). ``flatfield_empty_threshold`` (default
``0.0``) fixes this: voxels ``<=`` it are treated as no-data and filled with the
valid-voxel median before the estimate, keeping it flat across the interface. ``0.0``
catches exactly-zero fill; raise it to the empty region's intensity ceiling if the
"empty" area is faintly non-zero (e.g. ``"flatfield_empty_threshold": 5.0``). The run
logs how many no-data voxels were filled.

Performance
-----------
The gfp-mask "model" is a classical cupy routine, not a deep net. Its
labeling/morphology steps stall the GPU on host syncs, so GPU *utilization* reads low
even when the GPU stage is the bottleneck — judge by wall-clock and the bottleneck
verdict logged from ``--metrics-json``, not by ``nvidia-smi`` utilization.

Tips:
- Don't over-enlarge ``--patch``: huge patches take longer for the prep workers to
  build and leave fewer in flight, which *starves* the GPU between patches and lowers
  throughput. Keep patch moderate (e.g. 64-128 per axis).
- Biggest win: run several GPU workers per device to overlap one worker's host-sync
  stalls with another's compute, via ``--workers-per-device 3`` (try this first). Costs
  ~N x GPU memory.
"""

import argparse
import asyncio
import copy
import itertools
import json
import logging
import multiprocessing
import re
import statistics
import sys
from collections import deque
from concurrent.futures import ThreadPoolExecutor
from typing import List, Optional, Tuple
from urllib.parse import urlparse

import boto3
import numpy as np
import tensorstore as ts

from aind_torch_utils.config import InferenceConfig
from aind_torch_utils.correction import BackgroundField, fill_no_data
from aind_torch_utils.labeling import UnionFind, block_ranges, union_faces
from aind_torch_utils.postprocessing import read_pipeline_params
from aind_torch_utils.run import load_model, run
from aind_torch_utils.utils import open_ts_spec
from example_utils.utils import load_json

# Default input spec (sample at multiscale level 5) used when --in-spec is omitted.
DEFAULT_IN_SPEC = {
    "driver": "zarr",
    "kvstore": {
        "driver": "s3",
        "bucket": "aind-open-data",
        "path": (
            "HCR_831990-s2-ls1_2026-05-15_00-00-00_processed_2026-05-19_01-32-11"
            "/fusion/ch_488/fused.zarr/5/"
        ),
        "aws_region": "us-west-2",
    },
}
DOWNSAMPLE_METHOD = "max"  # keeps coarser mask levels strictly binary
# Instance-label pyramid reducer: labels must not be max/mean-reduced (invents IDs);
# "stride" (nearest) preserves exact IDs. Paired with a uint32 output dtype.
LABEL_DOWNSAMPLE_METHOD = "stride"
# Max per-axis size for the (low-frequency) flat-field estimate; larger coarse levels
# are stride-subsampled to this before the GPU morphology, to avoid OOM.
FLATFIELD_MAX_DIM = 256

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


def _open_or_create_s3_mask_zarr(
    bucket: str, path: str, shape, chunks, region: str
) -> ts.TensorStore:
    """Open (or create) a uint8 zarr2 array for the output mask on S3."""
    spec = {
        "driver": "zarr",
        "kvstore": {
            "driver": "s3",
            "bucket": bucket,
            "path": path,
            "aws_region": region,
        },
        "metadata": {
            "shape": list(shape),
            "chunks": list(chunks),
            "dtype": "|u1",  # uint8 mask
            "dimension_separator": "/",
        },
        "create": True,
        "delete_existing": True,
    }
    return ts.open(spec).result()


def _load_spec_dict(spec) -> dict:
    """Return a spec as a dict, mirroring open_ts_spec's input handling.

    Accepts a dict, a raw JSON string, or a path to a JSON file.
    """
    if isinstance(spec, str):
        stripped = spec.lstrip()
        if stripped.startswith("{") or stripped.startswith("["):
            return json.loads(stripped)
        with open(spec, "r", encoding="utf-8") as f:
            return json.load(f)
    return spec


def _kvstore_bucket_path(spec_dict: dict) -> Tuple[str, str, Optional[str]]:
    """Extract (bucket, path, aws_region) from a spec's kvstore.

    Handles both the dict form ({"driver": "s3", "bucket": ..., "path": ...}) and the
    shorthand string form ("s3://bucket/key").
    """
    kv = spec_dict.get("kvstore", spec_dict)
    if isinstance(kv, str):
        parsed = urlparse(kv)
        return parsed.netloc, parsed.path.lstrip("/"), None
    return kv.get("bucket", ""), kv.get("path", "").strip("/"), kv.get("aws_region")


def _scale_zyx(ds: dict) -> Optional[List[float]]:
    """Return the ZYX scale of a multiscales dataset entry, or None."""
    for ct in ds.get("coordinateTransformations", []):
        if ct.get("type") == "scale":
            return list(ct["scale"][-3:])
    return None


def _read_source_multiscales(
    bucket: str, group_path: str
) -> Optional[Tuple[dict, list, Optional[dict]]]:
    """Read the source OME-Zarr group's first multiscales block.

    Returns ``(multiscale_dict, datasets, omero)`` or ``None`` if the group has no
    multiscales metadata. Handles zarr v3 (``zarr.json``) and v2 (``.zattrs``).
    """
    group_uri = f"s3://{bucket}/{group_path}"
    attrs = None
    for fname in ("zarr.json", ".zattrs"):
        try:
            attrs = load_json(group_uri, fname)
            logger.info("Read OME metadata from %s/%s", group_uri, fname)
            break
        except Exception:
            continue
    if attrs is None:
        logger.warning("No zarr.json/.zattrs found at %s", group_uri)
        return None

    # zarr v3 nests user attributes under "attributes"; OME under "ome".
    attrs = attrs.get("attributes", attrs)
    ome = attrs.get("ome", attrs)
    multiscales = ome.get("multiscales", [])
    if not multiscales:
        return None
    ms = multiscales[0]
    return ms, ms.get("datasets", []), ome.get("omero")


def _spec_with_level(spec, new_level) -> dict:
    """Return a copy of the input spec whose kvstore path points at ``new_level``.

    Replaces the trailing ``/<level>`` of the kvstore path so the coarse pyramid level
    used for background estimation is read from the same OME-Zarr group.
    """
    spec_dict = copy.deepcopy(_load_spec_dict(spec))
    kv = spec_dict.get("kvstore", spec_dict)
    if isinstance(kv, str):
        new_kv = re.sub(r"/\d+/?$", f"/{new_level}/", kv.rstrip("/") + "/")
        if "kvstore" in spec_dict:
            spec_dict["kvstore"] = new_kv
        else:
            return new_kv  # shorthand spec was itself the kvstore string
    else:
        path = kv.get("path", "").rstrip("/")
        kv["path"] = re.sub(r"/\d+$", f"/{new_level}", path) + "/"
    return spec_dict


def _estimate_background(spec, cfg, processing_shape: Tuple[int, int, int]):
    """Estimate a coarse global flat-field background for white top-hat correction.

    Reads the whole (small) ``cfg.flatfield_level`` volume and removes sparse bright
    cells with a grey-opening + optional Gaussian smoothing, so the estimate captures
    only the low-frequency shading / fusion inhomogeneity. The field is kept at the
    *coarse* resolution (a few MB) and interpolated up per-block inside PrepWorker, so
    the full-resolution background of the whole volume is never materialized (which
    would be tens of GB at fine processing levels). Returns a :class:`BackgroundField`
    (coarse array + processing/coarse scale per axis), or ``None`` if disabled.

    The field is global and sampled by absolute coordinates, so neighboring blocks see
    identical values and the correction adds no seams.
    """
    if not cfg.flatfield:
        return None

    import cupy as cp
    import cupyx.scipy.ndimage as cndi

    coarse_spec = _spec_with_level(spec, cfg.flatfield_level)
    coarse_store = open_ts_spec(coarse_spec)
    # Read in the native dtype (e.g. uint16, 2 bytes); do NOT float32-cast the full
    # volume — that would double the host footprint. We cast only the subsampled array.
    coarse = coarse_store[cfg.t_idx, cfg.c_idx].read().result()
    logger.info(
        "Flat-field: read coarse level %s shape=%s dtype=%s (~%.2f GB)",
        cfg.flatfield_level,
        coarse.shape,
        coarse.dtype,
        coarse.nbytes / 1e9,
    )

    # The background is low-frequency, so cap its resolution before the GPU morphology
    # to avoid OOM when flatfield_level is still large. Stride-subsample on the host
    # (cheap view), then cast just the small array to float32 on the GPU. The opening
    # radius and sigma are divided by the stride so the physical extent is preserved.
    step = max(1, (max(coarse.shape) + FLATFIELD_MAX_DIM - 1) // FLATFIELD_MAX_DIM)
    if step > 1:
        coarse = coarse[::step, ::step, ::step]
        logger.info(
            "Flat-field: subsampled estimate to %s (stride %d) to fit the GPU.",
            coarse.shape,
            step,
        )

    # Fill no-data (empty fused regions) with the valid-voxel median before the
    # morphology, so the empty/tissue interface doesn't drag the background down and
    # leave a bright rim there under subtract correction.
    filled = fill_no_data(coarse, cfg.flatfield_empty_threshold)
    if filled is not coarse:
        n_empty = int((coarse <= cfg.flatfield_empty_threshold).sum())
        logger.info(
            "Flat-field: filled %d no-data voxels (<= %g) with the valid median.",
            n_empty,
            cfg.flatfield_empty_threshold,
        )
        coarse = filled

    cg = cp.asarray(coarse).astype(cp.float32)
    radius = int(round(cfg.flatfield_opening_radius / step))
    if cfg.flatfield_opening_radius > 0 and radius > 0:
        size = 2 * radius + 1
        cg = cndi.grey_opening(cg, size=(size, size, size))
    if cfg.flatfield_sigma > 0:
        cg = cndi.gaussian_filter(cg, sigma=float(cfg.flatfield_sigma) / step)

    field = cp.asnumpy(cg)
    # Processing-level voxels per coarse voxel, per axis.
    scale = tuple(float(p) / float(c) for p, c in zip(processing_shape, field.shape))
    logger.info(
        "Flat-field: coarse background ready shape=%s scale=%s", field.shape, scale
    )
    return BackgroundField(field=field, scale=scale)


async def _gather_bounded(ranges, make_coro, limit: int) -> None:
    """Run ``make_coro(*r)`` for each range, keeping at most ``limit`` tasks in flight.

    A sliding window rather than a per-batch barrier: a new task starts as soon as any
    finishes, so slow S3 round-trips don't stall the rest (this step is latency-bound,
    so a high ``limit`` is what hides the per-request latency). Exceptions propagate.
    """
    pending: set = set()
    for r in ranges:
        if len(pending) >= limit:
            done, pending = await asyncio.wait(
                pending, return_when=asyncio.FIRST_COMPLETED
            )
            for d in done:
                d.result()  # surface any exception immediately
        pending.add(asyncio.create_task(make_coro(*r)))
    if pending:
        await asyncio.gather(*pending)


def _build_mask_pyramid(
    bucket: str,
    base_path: str,
    datasets_from_l: list,
    region: str,
    chunk: int = 128,
    concurrency: int = 64,
    copy_concurrency: int = 16,
    reducer: str = DOWNSAMPLE_METHOD,
    dtype: str = "|u1",
) -> None:
    """Generate coarser mask levels by downsampling the segmented level.

    ``datasets_from_l`` is the source multiscales datasets sliced from level L
    onward; index 0 is the already-written segmented level. Each subsequent level is
    produced from the previous one with the ``reducer`` downsample method and written as
    ``dtype`` at the source's original ``path`` string. Defaults keep the binary-mask
    behavior (``max`` reducer, ``uint8``); instance labels pass ``stride``/``|u4``.
    """

    def _factors(prev_ds: dict, ds: dict) -> List[int]:
        s_prev, s_cur = _scale_zyx(prev_ds), _scale_zyx(ds)
        if s_prev is None or s_cur is None:
            raise ValueError("Source datasets are missing scale transforms.")
        return [max(1, round(s_cur[a] / s_prev[a])) for a in range(3)]

    async def _build_levels():
        ctx = ts.Context({"data_copy_concurrency": {"limit": copy_concurrency}})

        for i in range(1, len(datasets_from_l)):
            prev_ds, ds = datasets_from_l[i - 1], datasets_from_l[i]
            sf_padded = [1, 1] + _factors(prev_ds, ds)

            downsampled = await ts.open(
                {
                    "driver": "downsample",
                    "downsample_factors": sf_padded,
                    "downsample_method": reducer,
                    "base": {
                        "driver": "zarr",
                        "kvstore": {
                            "driver": "s3",
                            "bucket": bucket,
                            "path": f"{base_path}{prev_ds['path']}/",
                            "aws_region": region,
                        },
                    },
                },
                context=ctx,
            )
            new_shape = list(downsampled.shape)
            nz, ny, nx = new_shape[2], new_shape[3], new_shape[4]
            cz, cy, cx = min(chunk, nz), min(chunk, ny), min(chunk, nx)

            output = await ts.open(
                {
                    "driver": "zarr",
                    "kvstore": {
                        "driver": "s3",
                        "bucket": bucket,
                        "path": f"{base_path}{ds['path']}/",
                        "aws_region": region,
                    },
                    "metadata": {
                        "shape": new_shape,
                        "chunks": [1, 1, cz, cy, cx],
                        "dtype": dtype,
                        "dimension_separator": "/",
                    },
                    "create": True,
                    "delete_existing": True,
                },
                context=ctx,
            )

            async def _copy(z0, z1, y0, y1, x0, x1):
                data = await downsampled[:, :, z0:z1, y0:y1, x0:x1].read()
                await output[:, :, z0:z1, y0:y1, x0:x1].write(data)
                del data

            ranges = [
                (z0, min(z0 + cz, nz), y0, min(y0 + cy, ny), x0, min(x0 + cx, nx))
                for z0 in range(0, nz, cz)
                for y0 in range(0, ny, cy)
                for x0 in range(0, nx, cx)
            ]
            await _gather_bounded(ranges, _copy, concurrency)
            logger.info("[pyramid] wrote level %s shape=%s", ds["path"], new_shape)

    asyncio.run(_build_levels())


async def _upsample_run(
    bucket,
    base_path,
    region,
    coarse_path,
    fine_path,
    clen,
    factors,
    ranges,
    concurrency,
    copy_concurrency,
) -> None:
    """Nearest-upsample a set of fine-level chunk ranges on one event loop.

    Reads the coarse level and writes into the *already-created* fine level (the parent
    writes the fine level's metadata first). Shared by the single-process path and by
    each ``--pyramid-processes`` worker, so both use the identical gather.
    """
    ctx = ts.Context({"data_copy_concurrency": {"limit": copy_concurrency}})
    coarse = await ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{coarse_path}",
                "aws_region": region,
            },
        },
        context=ctx,
    )
    output = await ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{fine_path}",
                "aws_region": region,
            },
        },
        context=ctx,
    )
    fz, fy, fx = factors

    async def _copy(z0, z1, y0, y1, x0, x1):
        # Per-axis nearest source indices (floor-div, clamped to end).
        iz = np.minimum(np.arange(z0, z1) // fz, clen[2] - 1)
        iy = np.minimum(np.arange(y0, y1) // fy, clen[3] - 1)
        ix = np.minimum(np.arange(x0, x1) // fx, clen[4] - 1)
        sz0, sz1 = int(iz[0]), int(iz[-1]) + 1
        sy0, sy1 = int(iy[0]), int(iy[-1]) + 1
        sx0, sx1 = int(ix[0]), int(ix[-1]) + 1
        sub = await coarse[:, :, sz0:sz1, sy0:sy1, sx0:sx1].read()
        # Gather nearest voxels onto the fine grid (exact, edge-clamped).
        up = sub[np.ix_([0], [0], iz - sz0, iy - sy0, ix - sx0)]
        await output[:, :, z0:z1, y0:y1, x0:x1].write(up)
        del sub, up

    await _gather_bounded(ranges, _copy, concurrency)


def _upsample_shard(task) -> None:
    """multiprocessing entry point: upsample one shard of a level's chunk ranges.

    A separate process (spawn) gives its own TensorStore context + event loop, so the
    S3 request streams are genuinely independent -> N processes ~= N x the aggregate
    request rate, which is what saturates this latency-bound step across CPU cores.
    """
    asyncio.run(_upsample_run(*task))


def _open_fine_level(
    bucket, base_path, fine_path, region, nz, ny, nx, cz, cy, cx, dtype="|u1"
):
    """Create (or reset) the fine level's zarr metadata; workers reopen it to write."""
    ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{fine_path}",
                "aws_region": region,
            },
            "metadata": {
                "shape": [1, 1, nz, ny, nx],
                "chunks": [1, 1, cz, cy, cx],
                "dtype": dtype,
                "dimension_separator": "/",
            },
            "create": True,
            "delete_existing": True,
        }
    ).result()


def _upsample_mask_pyramid(
    bucket: str,
    base_path: str,
    spec,
    datasets_upto_l: list,
    region: str,
    chunk: int = 128,
    concurrency: int = 64,
    copy_concurrency: int = 16,
    processes: int = 1,
    dtype: str = "|u1",
) -> None:
    """Fill finer pyramid levels (0..L-1) by nearest-upsampling the segmented level.

    ``datasets_upto_l`` is the source multiscales datasets for levels 0..L (index 0 is
    the finest, index -1 is the already-written segmented level L). Each finer level is
    produced from the previous (just-written) coarser one by nearest-neighbour
    upsampling (the mask is binary, so never interpolate). Output shapes are taken from
    the *source* arrays at each level so the mask aligns with the data. TensorStore has
    no upsample driver, so this reads the coarse level, gathers nearest voxels, and
    writes the fine level, streamed chunk-by-chunk (numpy only, no GPU).

    ``processes > 1`` shards each level's chunk ranges across that many worker processes
    (spawned), each with its own TensorStore context/event loop, to parallelize the
    S3-latency-bound writes across CPU cores. Total in-flight requests ~=
    ``processes * concurrency``. Levels stay sequential (each reads the previous one).
    """

    def _up_factors(coarse_ds: dict, fine_ds: dict) -> List[int]:
        s_coarse, s_fine = _scale_zyx(coarse_ds), _scale_zyx(fine_ds)
        if s_coarse is None or s_fine is None:
            raise ValueError("Source datasets are missing scale transforms.")
        return [max(1, round(s_coarse[a] / s_fine[a])) for a in range(3)]

    # Walk from level L (last) toward level 0; each finer level reads the previous.
    for i in range(len(datasets_upto_l) - 2, -1, -1):
        coarse_ds, fine_ds = datasets_upto_l[i + 1], datasets_upto_l[i]
        factors = tuple(_up_factors(coarse_ds, fine_ds))
        coarse_path, fine_path = f"{coarse_ds['path']}/", f"{fine_ds['path']}/"

        coarse = ts.open(
            {
                "driver": "zarr",
                "kvstore": {
                    "driver": "s3",
                    "bucket": bucket,
                    "path": f"{base_path}{coarse_path}",
                    "aws_region": region,
                },
            }
        ).result()
        clen = tuple(int(s) for s in coarse.shape)  # (1, 1, Cz, Cy, Cx)

        # Target shape from the *source* fine level so the mask aligns w/ data.
        src_fine = open_ts_spec(_spec_with_level(spec, fine_ds["path"]))
        nz, ny, nx = (int(s) for s in src_fine.domain.shape[-3:])
        cz, cy, cx = min(chunk, nz), min(chunk, ny), min(chunk, nx)

        # Create the fine level's metadata once in the parent; workers reopen to write.
        _open_fine_level(
            bucket, base_path, fine_path, region, nz, ny, nx, cz, cy, cx, dtype=dtype
        )

        ranges = [
            (z0, min(z0 + cz, nz), y0, min(y0 + cy, ny), x0, min(x0 + cx, nx))
            for z0 in range(0, nz, cz)
            for y0 in range(0, ny, cy)
            for x0 in range(0, nx, cx)
        ]
        common = (bucket, base_path, region, coarse_path, fine_path, clen, factors)
        if processes and processes > 1:
            shards = [ranges[p::processes] for p in range(processes)]
            tasks = [
                common + (shard, concurrency, copy_concurrency)
                for shard in shards
                if shard
            ]
            ctxmp = multiprocessing.get_context("spawn")
            with ctxmp.Pool(len(tasks)) as pool:
                pool.map(_upsample_shard, tasks)
        else:
            asyncio.run(_upsample_run(*common, ranges, concurrency, copy_concurrency))
        logger.info(
            "[upsample] wrote level %s shape=%s (%d chunks, %d procs)",
            fine_ds["path"],
            [1, 1, nz, ny, nx],
            len(ranges),
            max(1, processes),
        )


def _face_planes(labels, cp) -> dict:
    """The 6 boundary planes of a labeled block as host arrays (for seam stitching)."""
    return {
        "zlo": cp.asnumpy(labels[0]),
        "zhi": cp.asnumpy(labels[-1]),
        "ylo": cp.asnumpy(labels[:, 0]),
        "yhi": cp.asnumpy(labels[:, -1]),
        "xlo": cp.asnumpy(labels[:, :, 0]),
        "xhi": cp.asnumpy(labels[:, :, -1]),
    }


def _stitch_faces(uf, blocks, metas, shifts=None) -> None:
    """Union global labels across shared block faces (each block's +Z/+Y/+X neighbour).

    ``shifts`` selects the seam connectivity (passed through to ``union_faces``): the
    default 3x3 neighbourhood is 26-connectivity (foreground); ``[(0, 0)]`` is
    6-connectivity (background hole-fill).
    """

    def _glob(face, off):
        g = face.astype(np.int64)
        return np.where(g > 0, g + off, 0)

    by_coord = {(b[0], b[2], b[4]): b for b in blocks}
    for blk in blocks:
        z0, z1, y0, y1, x0, x1 = blk
        off_a = metas[blk]["off"]
        for hi, lo, nbr in (
            ("zhi", "zlo", (z1, y0, x0)),
            ("yhi", "ylo", (z0, y1, x0)),
            ("xhi", "xlo", (z0, y0, x1)),
        ):
            nb = by_coord.get(nbr)
            if nb is None:
                continue
            union_faces(
                uf,
                _glob(metas[blk][hi], off_a),
                _glob(metas[nb][lo], metas[nb]["off"]),
                shifts=shifts,
            )


def _border_locals(blk, labels, shape, cp) -> np.ndarray:
    """Local labels on block faces that coincide with the volume's outer border."""
    nz, ny, nx = shape
    z0, z1, y0, y1, x0, x1 = blk
    planes = []
    if z0 == 0:
        planes.append(labels[0])
    if z1 == nz:
        planes.append(labels[-1])
    if y0 == 0:
        planes.append(labels[:, 0])
    if y1 == ny:
        planes.append(labels[:, -1])
    if x0 == 0:
        planes.append(labels[:, :, 0])
    if x1 == nx:
        planes.append(labels[:, :, -1])
    if not planes:
        return np.empty(0, dtype=np.int64)
    u = cp.unique(cp.concatenate([p.ravel() for p in planes]))
    return cp.asnumpy(u[u > 0]).astype(np.int64)


def _hysteresis_connect(
    bucket: str,
    base_path: str,
    seed_src_path: str,
    final_path: str,
    region: str,
    block: int = 512,
    chunk: int = 128,
    readahead: int = 8,
) -> None:
    """Collapse a 2-level mask {0,1,2} into a binary mask by seam-correct hysteresis.

    Keeps 26-connected components of the grow mask (``m >= 1``) that contain >=1
    seed (``m == 2``). Labels each block on the GPU with cucim, stitches labels across
    block faces with a union-find, propagates seed membership to component roots, then
    re-labels each block and writes the binary result. Correct across block seams and
    streamed block-by-block (no full int32 label volume is materialized).
    """
    import cupy as cp
    from cucim.skimage.measure import label as cucim_label

    ctx = ts.Context({"data_copy_concurrency": {"limit": 4}})
    src = ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{seed_src_path}",
                "aws_region": region,
            },
        },
        context=ctx,
    ).result()
    nz, ny, nx = (int(s) for s in src.domain.shape[-3:])

    blocks = [
        (z0, z1, y0, y1, x0, x1)
        for (z0, z1) in block_ranges(nz, block)
        for (y0, y1) in block_ranges(ny, block)
        for (x0, x1) in block_ranges(nx, block)
    ]

    def _label_host(m_host):
        m = cp.asarray(m_host)
        labels, k = cucim_label(m >= 1, return_num=True, connectivity=3)
        # int32 labels: local labels < block^3 < 2^31, so the per-block faces stored in
        # `metas` (all blocks held at once) use half the RAM/VRAM of int64. Global
        # labels (local + offset) can exceed 2^31, so offset math promotes to int64.
        return m, labels.astype(cp.int32), int(k)

    # Pass A: label each block, record counts/offsets, seed labels, and 6 face planes.
    # Reads are prefetched (see _prefetch_blocks) to overlap S3 latency with GPU work.
    metas = {}
    offset = 0
    for blk, m_host in _prefetch_blocks(src, blocks, readahead):
        m, labels, k = _label_host(m_host)
        seed = cp.unique(labels[m == 2])
        seed = seed[seed > 0]
        metas[blk] = {
            "off": offset,
            "seed": cp.asnumpy(seed),
            **_face_planes(labels, cp),
        }
        offset += k
        del m, labels
    total = offset
    logger.info("[hysteresis] %d blocks, %d raw components", len(blocks), total)

    # Union-find over global labels + seed flags.
    uf = UnionFind(total + 1)
    seeded = np.zeros(total + 1, dtype=bool)
    for meta in metas.values():
        seeded[meta["seed"].astype(np.int64) + meta["off"]] = True

    _stitch_faces(uf, blocks, metas)

    roots = uf.flatten_roots()
    root_seeded = np.zeros(total + 1, dtype=bool)
    np.logical_or.at(root_seeded, roots, seeded)
    keep = root_seeded[roots]
    keep[0] = False  # background

    # Pass B: re-label each block, map to root, write the kept (binary) mask.
    cz, cy, cx = min(chunk, nz), min(chunk, ny), min(chunk, nx)
    out = ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{final_path}",
                "aws_region": region,
            },
            "metadata": {
                "shape": [1, 1, nz, ny, nx],
                "chunks": [1, 1, cz, cy, cx],
                "dtype": "|u1",
                "dimension_separator": "/",
            },
            "create": True,
            "delete_existing": True,
        },
        context=ctx,
    ).result()
    keep_gpu = cp.asarray(keep)
    for blk, m_host in _prefetch_blocks(src, blocks, readahead):
        z0, z1, y0, y1, x0, x1 = blk
        _, labels, _ = _label_host(m_host)
        # Promote to int64 before adding the offset: global labels can exceed 2^31.
        gl = cp.where(labels > 0, labels.astype(cp.int64) + metas[blk]["off"], 0)
        out_block = keep_gpu[gl].astype(cp.uint8)
        out[0, 0, z0:z1, y0:y1, x0:x1].write(cp.asnumpy(out_block)).result()
        del labels, gl, out_block
    logger.info(
        "[hysteresis] wrote binary mask to %s%s (%d seeded components)",
        base_path,
        final_path,
        int(root_seeded.sum()),
    )


def _fill_holes_connect(
    bucket: str,
    base_path: str,
    src_path: str,
    final_path: str,
    region: str,
    block: int = 512,
    chunk: int = 128,
    max_hole_size: Optional[int] = None,
    readahead: int = 8,
) -> None:
    """Fill enclosed cavities in a binary mask, seam-correct across block faces.

    A "hole" is a 6-connected background component (``m == 0``) that does **not** reach
    the volume's outer border. Background is labeled per block on the GPU, labels are
    stitched across faces with a union-find (6-connectivity, the topological complement
    of the 26-connected foreground), and any background component whose root never
    touches the volume boundary -- and (when ``max_hole_size`` is set) is no larger than
    ``max_hole_size`` voxels -- is filled to foreground. Streamed block-by-block (no
    full int32 label volume is materialized).
    """
    import cupy as cp
    from cucim.skimage.measure import label as cucim_label

    ctx = ts.Context({"data_copy_concurrency": {"limit": 4}})
    src = ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{src_path}",
                "aws_region": region,
            },
        },
        context=ctx,
    ).result()
    nz, ny, nx = (int(s) for s in src.domain.shape[-3:])

    blocks = [
        (z0, z1, y0, y1, x0, x1)
        for (z0, z1) in block_ranges(nz, block)
        for (y0, y1) in block_ranges(ny, block)
        for (x0, x1) in block_ranges(nx, block)
    ]

    def _label_host(m_host):
        m = cp.asarray(m_host)
        labels, k = cucim_label(m == 0, return_num=True, connectivity=1)
        # int32 labels halve the per-block face RAM/VRAM (all blocks' faces are held in
        # `metas` at once); global labels (local + offset) are promoted to int64 below.
        return m, labels.astype(cp.int32), int(k)

    # Pass A: label background per block; record offsets, sizes, border + face labels.
    # Reads are prefetched (see _prefetch_blocks) to overlap S3 latency with GPU work.
    shape = (nz, ny, nx)
    metas = {}
    offset = 0
    for blk, m_host in _prefetch_blocks(src, blocks, readahead):
        m, labels, k = _label_host(m_host)
        counts = cp.asnumpy(cp.bincount(labels.ravel(), minlength=k + 1))
        k1 = k + 1
        metas[blk] = {
            "off": offset,
            "k": k,
            "counts": counts[1:k1].astype(np.int64),  # sizes of local labels 1..k
            "border": _border_locals(blk, labels, shape, cp),
            **_face_planes(labels, cp),
        }
        offset += k
        del m, labels
    total = offset
    logger.info("[fill-holes] %d blocks, %d background components", len(blocks), total)

    # Per-global-label sizes and which labels touch the volume boundary.
    sizes = np.zeros(total + 1, dtype=np.int64)
    border = np.zeros(total + 1, dtype=bool)
    for meta in metas.values():
        off, k = meta["off"], meta["k"]
        lo = off + 1
        hi = lo + k
        sizes[lo:hi] = meta["counts"]
        if meta["border"].size:
            border[meta["border"] + off] = True

    # Union-find over global labels, stitching across faces with 6-connectivity.
    uf = UnionFind(total + 1)
    _stitch_faces(uf, blocks, metas, shifts=[(0, 0)])

    roots = uf.flatten_roots()
    root_border = np.zeros(total + 1, dtype=bool)
    np.logical_or.at(root_border, roots, border)
    root_size = np.zeros(total + 1, dtype=np.int64)
    np.add.at(root_size, roots, sizes)
    fillable_root = ~root_border
    if max_hole_size:
        fillable_root &= root_size <= max_hole_size
    fill = fillable_root[roots]
    fill[0] = False  # label 0 = foreground in the background labeling; never a hole

    # Pass B: re-label background, map to root, write (foreground OR filled-hole).
    cz, cy, cx = min(chunk, nz), min(chunk, ny), min(chunk, nx)
    out = ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{final_path}",
                "aws_region": region,
            },
            "metadata": {
                "shape": [1, 1, nz, ny, nx],
                "chunks": [1, 1, cz, cy, cx],
                "dtype": "|u1",
                "dimension_separator": "/",
            },
            "create": True,
            "delete_existing": True,
        },
        context=ctx,
    ).result()
    fill_gpu = cp.asarray(fill)
    for blk, m_host in _prefetch_blocks(src, blocks, readahead):
        z0, z1, y0, y1, x0, x1 = blk
        m, labels, _ = _label_host(m_host)
        # Promote to int64 before adding the offset: global labels can exceed 2^31.
        gl = cp.where(labels > 0, labels.astype(cp.int64) + metas[blk]["off"], 0)
        out_block = ((m >= 1) | fill_gpu[gl]).astype(cp.uint8)
        out[0, 0, z0:z1, y0:y1, x0:x1].write(cp.asnumpy(out_block)).result()
        del m, labels, gl, out_block
    logger.info(
        "[fill-holes] wrote binary mask to %s%s (%d holes filled)",
        base_path,
        final_path,
        int(fillable_root[1:].sum()),
    )


def _mask_has_foreground(
    bucket: str, base_path: str, path: str, region: str, block: int = 512
) -> bool:
    """True if the mask at ``path`` has any nonzero voxel.

    Scans blocks (host reads, cheap ``max`` reduction) and returns at the first
    foreground block, so a non-blank mask is detected quickly; a fully blank one is
    confirmed only after a full scan (unavoidable), which still saves the far more
    expensive post-processing + pyramid that would otherwise run on nothing.
    """
    src = ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{path}",
                "aws_region": region,
            },
        }
    ).result()
    nz, ny, nx = (int(s) for s in src.domain.shape[-3:])
    for z0, z1 in block_ranges(nz, block):
        for y0, y1 in block_ranges(ny, block):
            for x0, x1 in block_ranges(nx, block):
                blk = src[0, 0, z0:z1, y0:y1, x0:x1].read().result()
                if blk.max() > 0:
                    return True
    return False


def _prefetch_blocks(src, blocks, readahead: int):
    """Yield ``(blk, host_ndarray)`` with up to ``readahead`` S3 reads in flight.

    The CCL passes are S3-latency-bound (sequential reads leave the GPU/CPU idle).
    Reader threads fetch upcoming blocks while the caller's GPU work runs on the main
    thread, overlapping the reads. Blocks are yielded in input order (offsets stable).
    """

    def _read(blk):
        z0, z1, y0, y1, x0, x1 = blk
        return src[0, 0, z0:z1, y0:y1, x0:x1].read().result()

    with ThreadPoolExecutor(max_workers=max(1, readahead)) as ex:
        it = iter(blocks)
        pending = deque(
            (blk, ex.submit(_read, blk))
            for blk in itertools.islice(it, max(1, readahead))
        )
        for nxt in it:
            blk, fut = pending.popleft()
            pending.append((nxt, ex.submit(_read, nxt)))
            yield blk, fut.result()
        while pending:
            blk, fut = pending.popleft()
            yield blk, fut.result()


def _instance_connect(
    bucket: str,
    base_path: str,
    src_path: str,
    final_path: str,
    region: str,
    block: int = 512,
    chunk: int = 128,
    min_size: int = 0,
    readahead: int = 8,
) -> None:
    """Label connected objects of a binary mask with unique IDs (instance segmentation).

    26-connected components of the foreground (``m >= 1``) each get a unique compact ID
    ``1..N`` in a ``uint32`` volume (background stays 0). Uses the same seam-correct
    chunked-GPU-CCL + union-find machinery as hysteresis/hole-fill, so an object across
    block faces gets one ID. Components smaller than ``min_size`` voxels are dropped
    (set to 0). Streamed block-by-block; no full label volume is materialized.
    """
    import cupy as cp
    from cucim.skimage.measure import label as cucim_label

    ctx = ts.Context({"data_copy_concurrency": {"limit": 4}})
    src = ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{src_path}",
                "aws_region": region,
            },
        },
        context=ctx,
    ).result()
    nz, ny, nx = (int(s) for s in src.domain.shape[-3:])

    blocks = [
        (z0, z1, y0, y1, x0, x1)
        for (z0, z1) in block_ranges(nz, block)
        for (y0, y1) in block_ranges(ny, block)
        for (x0, x1) in block_ranges(nx, block)
    ]

    def _label_host(m_host):
        m = cp.asarray(m_host)
        labels, k = cucim_label(m >= 1, return_num=True, connectivity=3)
        return labels.astype(cp.int32), int(k)

    # Pass A: label each block; record offsets, faces, and (for min_size) voxel counts.
    # Reads are prefetched so S3 latency overlaps the GPU labeling (blocks stay in
    # order, so `offset` assignment is identical here and in Pass B).
    metas = {}
    offset = 0
    for blk, m_host in _prefetch_blocks(src, blocks, readahead):
        labels, k = _label_host(m_host)
        meta = {"off": offset, "k": k, **_face_planes(labels, cp)}
        if min_size > 0:
            k1 = k + 1
            counts = cp.asnumpy(cp.bincount(labels.ravel(), minlength=k1))
            meta["counts"] = counts[1:k1].astype(np.int64)
        metas[blk] = meta
        offset += k
        del labels
    total = offset
    logger.info("[instances] %d blocks, %d raw components", len(blocks), total)

    # Union-find over global labels, stitching across faces (26-connectivity).
    uf = UnionFind(total + 1)
    _stitch_faces(uf, blocks, metas)
    roots = uf.flatten_roots()

    # Keep foreground roots (optionally size-filtered) and assign compact IDs 1..N.
    keep = np.ones(total + 1, dtype=bool)
    keep[0] = False
    if min_size > 0:
        sizes = np.zeros(total + 1, dtype=np.int64)
        for meta in metas.values():
            lo = meta["off"] + 1
            hi = lo + meta["k"]
            sizes[lo:hi] = meta["counts"]
        root_size = np.zeros(total + 1, dtype=np.int64)
        np.add.at(root_size, roots, sizes)
        keep &= root_size[roots] >= min_size
    uniq = np.unique(roots[keep])
    n_obj = int(uniq.size)
    if n_obj >= 2**32:
        raise ValueError(
            f"{n_obj} objects exceed uint32 capacity; use a coarser level or uint64."
        )
    id_of_root = np.zeros(total + 1, dtype=np.uint32)
    id_of_root[uniq] = np.arange(1, n_obj + 1, dtype=np.uint32)
    label_to_id = id_of_root[roots]  # global label -> compact id (0 = bg / dropped)
    label_to_id[0] = 0

    # Pass B: re-label each block, map to the compact ID, write uint32.
    cz, cy, cx = min(chunk, nz), min(chunk, ny), min(chunk, nx)
    out = ts.open(
        {
            "driver": "zarr",
            "kvstore": {
                "driver": "s3",
                "bucket": bucket,
                "path": f"{base_path}{final_path}",
                "aws_region": region,
            },
            "metadata": {
                "shape": [1, 1, nz, ny, nx],
                "chunks": [1, 1, cz, cy, cx],
                "dtype": "<u4",  # little-endian uint32 (| byte-order is 1-byte only)
                "dimension_separator": "/",
            },
            "create": True,
            "delete_existing": True,
        },
        context=ctx,
    ).result()
    id_gpu = cp.asarray(label_to_id)
    for blk, m_host in _prefetch_blocks(src, blocks, readahead):
        z0, z1, y0, y1, x0, x1 = blk
        labels, _ = _label_host(m_host)
        gl = cp.where(labels > 0, labels.astype(cp.int64) + metas[blk]["off"], 0)
        out_block = id_gpu[gl]
        out[0, 0, z0:z1, y0:y1, x0:x1].write(cp.asnumpy(out_block)).result()
        del labels, gl, out_block
    logger.info(
        "[instances] wrote %d objects to %s%s (uint32)", n_obj, base_path, final_path
    )


def _mask_stages(level: str, hysteresis: bool, fill_holes: bool, instance_labels: bool):
    """Ordered ``(name, path)`` post-seg stages; the last writes the canonical level.

    Earlier stages write ``{level}_<suffix>`` intermediates. The segmentation output is
    the 2-level "seed" mask when hysteresis is on, otherwise a binary "raw" mask. With
    ``instance_labels``, an ``instances`` stage is appended last (it relabels the final
    binary into unique uint32 IDs at the canonical level).
    """
    chain = [("seg", "seed" if hysteresis else "raw")]
    if hysteresis:
        chain.append(("hyst", "hyst"))
    if fill_holes:
        chain.append(("fill", "fill"))
    if instance_labels:
        chain.append(("instances", "instances"))
    last = len(chain) - 1
    return [
        (name, level if i == last else f"{level}_{suffix}")
        for i, (name, suffix) in enumerate(chain)
    ]


def _run_postprocess(args, base_path: str, stages) -> None:
    """Run the post-seg connectivity passes in order, then drop intermediates."""
    paths = dict(stages)
    max_hole = args.max_hole_size if args.max_hole_size > 0 else None
    prev = paths["seg"]
    if "hyst" in paths:
        logger.info("Hysteresis: %s -> %s%s/", prev, base_path, paths["hyst"])
        _hysteresis_connect(
            args.out_bucket,
            base_path,
            f"{prev}/",
            f"{paths['hyst']}/",
            args.aws_region,
            block=args.ccl_block,
            readahead=args.ccl_readahead,
        )
        prev = paths["hyst"]
    if "fill" in paths:
        logger.info("Fill holes: %s -> %s%s/", prev, base_path, paths["fill"])
        _fill_holes_connect(
            args.out_bucket,
            base_path,
            f"{prev}/",
            f"{paths['fill']}/",
            args.aws_region,
            block=args.ccl_block,
            max_hole_size=max_hole,
            readahead=args.ccl_readahead,
        )
        prev = paths["fill"]
    if "instances" in paths:
        logger.info("Instance labels: %s -> %s%s/", prev, base_path, paths["instances"])
        _instance_connect(
            args.out_bucket,
            base_path,
            f"{prev}/",
            f"{paths['instances']}/",
            args.aws_region,
            block=args.ccl_block,
            min_size=args.min_instance_size,
            readahead=args.ccl_readahead,
        )
    # Drop every non-final intermediate (the "seed" mask only if not kept).
    for name, path in stages[:-1]:
        if name == "seg" and args.keep_seed_mask:
            continue
        _delete_s3_prefix(args.out_bucket, f"{base_path}{path}/", args.aws_region)


def _write_output_group_metadata(
    bucket: str,
    base_path: str,
    source_ms: dict,
    datasets_from_l: list,
    omero: Optional[dict],
    region: str,
    reducer: str = DOWNSAMPLE_METHOD,
) -> None:
    """Write the zarr v2 group markers + OME-NGFF multiscales for the output.

    A valid OME-Zarr group needs both ``.zgroup`` (so readers like neuroglancer
    recognize it as a group) and ``.zattrs`` (the multiscales metadata). We copy the
    source multiscales block, replacing its datasets with ``datasets_from_l`` verbatim
    (original paths + absolute scales) so the mask aligns spatially with the source.
    """
    s3 = boto3.client("s3", region_name=region)

    # .zgroup — without this the group is not a valid zarr v2 group and viewers
    # silently ignore the multiscales metadata.
    s3.put_object(
        Bucket=bucket,
        Key=f"{base_path}.zgroup",
        Body=json.dumps({"zarr_format": 2}).encode(),
    )

    ms = dict(source_ms)
    ms["datasets"] = datasets_from_l
    # OME-NGFF readers (neuroglancer) require multiscales[].version to parse the
    # metadata; some source zarrs omit it (they carry "type"/"metadata" instead), so
    # ensure it is present.
    ms["version"] = ms.get("version") or "0.4"
    # We downsample the mask with our own reducer (max for binary, stride for labels),
    # not the source's.
    ms["type"] = reducer

    zattrs = {"multiscales": [ms]}
    if omero is not None:
        # Source omero describes intensities (e.g. window 0-65535), which makes a
        # binary {0,1} mask invisible; rescale the render window to the mask range.
        omero = json.loads(json.dumps(omero))  # deep copy before mutating
        for ch in omero.get("channels", []):
            ch["window"] = {"min": 0.0, "max": 1.0, "start": 0.0, "end": 1.0}
        zattrs["omero"] = omero
    s3.put_object(
        Bucket=bucket,
        Key=f"{base_path}.zattrs",
        Body=json.dumps(zattrs).encode(),
    )
    logger.info(
        "Wrote OME-NGFF group metadata (.zgroup + .zattrs) to s3://%s/%s",
        bucket,
        base_path,
    )


def _finalize_pyramid(
    args, base_path, spec, start, datasets, datasets_from_l, source_ms, omero
) -> None:
    """Build coarser levels (+ optional finer upsample) and write OME group metadata.

    In instance-label mode the canonical level is a uint32 label volume, so the pyramid
    uses a label-preserving reducer (``LABEL_DOWNSAMPLE_METHOD``) + uint32 and drops
    the (intensity-only) omero metadata; else the binary-mask defaults are unchanged.
    """
    label_mode = args.instance_labels
    reducer = LABEL_DOWNSAMPLE_METHOD if label_mode else DOWNSAMPLE_METHOD
    dtype = "<u4" if label_mode else "|u1"  # <u4 = little-endian uint32
    _build_mask_pyramid(
        args.out_bucket,
        base_path,
        datasets_from_l,
        args.aws_region,
        concurrency=args.pyramid_concurrency,
        copy_concurrency=args.pyramid_copy_concurrency,
        reducer=reducer,
        dtype=dtype,
    )

    fill_finer = args.fill_finer_levels and start > 0
    if args.fill_finer_levels and start == 0:
        logger.info("--fill-finer-levels: segmented level is already finest; nothing.")
    if fill_finer:
        _upsample_mask_pyramid(
            args.out_bucket,
            base_path,
            spec,
            datasets[: start + 1],
            args.aws_region,
            concurrency=args.pyramid_concurrency,
            copy_concurrency=args.pyramid_copy_concurrency,
            processes=args.pyramid_processes,
            dtype=dtype,
        )

    # Metadata lists every level when finer levels were filled, else L..N only.
    meta_datasets = datasets if fill_finer else datasets_from_l
    _write_output_group_metadata(
        args.out_bucket,
        base_path,
        source_ms,
        meta_datasets,
        None if label_mode else omero,
        args.aws_region,
        reducer=reducer,
    )


def _bottleneck_verdict(prep_fill: Optional[float], write_fill: Optional[float]) -> str:
    """Map queue fill ratios to a heuristic bottleneck verdict."""
    if prep_fill is None:
        return "No queue samples collected; cannot diagnose."
    if prep_fill < 0.25:
        return (
            "GPU starved -> prep/S3-bound. Try more --prep-workers, larger "
            "--block/--batch, or faster input reads."
        )
    if write_fill is not None and write_fill > 0.75:
        return "Writer/S3-write-bound (output writes back-pressure the pipeline)."
    if prep_fill > 0.75:
        return (
            "GPU/function-bound -> the masking function is the limiter (host syncs). "
            "Run more GPU workers per device, e.g. --workers-per-device 3."
        )
    return "Balanced / no single saturated stage."


def _summarize_metrics(path: str) -> None:
    """Read the pipeline metrics JSON and log a bottleneck verdict.

    Uses queue occupancy (a near-empty prep queue means the GPU is starved by
    prep/S3; a near-full prep or write queue points at the GPU/function or the
    writer). Thresholds are approximate guidance, not hard rules.
    """
    try:
        with open(path, "r", encoding="utf-8") as f:
            metrics = json.load(f)
    except (OSError, ValueError) as exc:
        logger.warning("Could not read metrics from %s: %s", path, exc)
        return

    queues = metrics.get("queue_monitor", {}).get("queues", {})

    def _fill(name_prefix: str) -> Optional[float]:
        ratios = []
        for name, q in queues.items():
            if not name.startswith(name_prefix):
                continue
            max_size = q.get("max_size") or 0
            sizes = [
                s["size"] for s in q.get("samples", []) if s.get("size") is not None
            ]
            if max_size > 0 and sizes:
                ratios.append(statistics.mean(sizes) / max_size)
        return statistics.mean(ratios) if ratios else None

    def _mean(values) -> Optional[float]:
        return statistics.mean(values) if values else None

    prep_fill = _fill("prep")
    write_fill = _fill("write")
    sysm = metrics.get("system_monitor", {})
    cpu_mean = _mean(sysm.get("cpu_percent") or [])
    recv_mean = _mean((sysm.get("net_io_mbytes_sec", {}) or {}).get("recv") or [])

    def _r(value, ndigits):
        return None if value is None else round(value, ndigits)

    logger.info(
        "Metrics: prep_fill=%s write_fill=%s cpu%%=%s net_recv_MBps=%s",
        _r(prep_fill, 2),
        _r(write_fill, 2),
        _r(cpu_mean, 1),
        _r(recv_mean, 1),
    )
    logger.info(
        "Bottleneck verdict (heuristic): %s",
        _bottleneck_verdict(prep_fill, write_fill),
    )


_FLATFIELD_KEYS = (
    "flatfield",
    "flatfield_mode",
    "flatfield_level",
    "flatfield_opening_radius",
    "flatfield_sigma",
    "flatfield_empty_threshold",
)


def _normalization_kwargs(params_json: Optional[str]) -> dict:
    """Build InferenceConfig normalization + flat-field kwargs from the params JSON.

    ``normalize="global"`` avoids the per-block percentile computation that
    bottlenecks prep, but requires literal min/max values (``norm_lower``/
    ``norm_upper``). Defaults to ``normalize="percentile"`` when no keys are given.
    Flat-field keys (``flatfield``/``flatfield_*``) are passed through verbatim to
    enable white top-hat background correction; ``flatfield=True`` requires
    ``flatfield_level``.
    """
    norm = read_pipeline_params(params_json)
    normalize = norm.get("normalize", "percentile")
    if normalize == "global" and (
        norm.get("norm_lower") is None or norm.get("norm_upper") is None
    ):
        raise ValueError(
            "normalize='global' requires norm_lower and norm_upper (global min/max) "
            "in --params-json."
        )
    kwargs = {"normalize": normalize}
    if norm.get("norm_lower") is not None:
        kwargs["norm_lower"] = norm["norm_lower"]
    if norm.get("norm_upper") is not None:
        kwargs["norm_upper"] = norm["norm_upper"]
    for key in _FLATFIELD_KEYS:
        if norm.get(key) is not None:
            kwargs[key] = norm[key]
    if kwargs.get("flatfield") and kwargs.get("flatfield_level") is None:
        raise ValueError(
            "flatfield=true requires flatfield_level (pyramid level to estimate the "
            "background from) in --params-json."
        )
    return kwargs


def _seed_threshold(params_json: Optional[str], threshold: float) -> Optional[float]:
    """Return the model's ``seed_threshold`` from params JSON, enabling hysteresis.

    ``None`` if absent. Warns (and still returns) if it is not strictly above
    ``threshold``, which would make the seed level degenerate.
    """
    if not params_json:
        return None
    with open(params_json) as f:
        seed = json.load(f).get("seed_threshold")
    if seed is not None and seed <= threshold:
        logger.warning(
            "seed_threshold (%s) <= threshold (%s); hysteresis seeds will be "
            "degenerate. Set seed_threshold > threshold.",
            seed,
            threshold,
        )
    return seed


def _model_threshold(params_json: Optional[str]) -> float:
    """Read the model ``threshold`` from params JSON (default matches the model)."""
    if not params_json:
        return 0.1
    with open(params_json) as f:
        return float(json.load(f).get("threshold", 0.1))


def _delete_s3_prefix(bucket: str, prefix: str, region: str) -> None:
    """Delete every object under an S3 prefix (used to drop the _seed intermediate)."""
    s3 = boto3.client("s3", region_name=region)
    paginator = s3.get_paginator("list_objects_v2")
    batch = []
    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
        for obj in page.get("Contents", []):
            batch.append({"Key": obj["Key"]})
            if len(batch) == 1000:
                s3.delete_objects(Bucket=bucket, Delete={"Objects": batch})
                batch = []
    if batch:
        s3.delete_objects(Bucket=bucket, Delete={"Objects": batch})
    logger.info("Deleted intermediate s3://%s/%s", bucket, prefix)


def _parse_args(argv: List[str]) -> argparse.Namespace:
    """Parse command-line arguments."""
    ap = argparse.ArgumentParser(
        description="Run the gfp-mask model on an S3 multiscale OME-Zarr."
    )
    ap.add_argument(
        "--in-spec",
        default=None,
        help=(
            "TensorStore JSON spec (file path or raw JSON). The level to segment is "
            "the trailing digit of its kvstore path. Defaults to the built-in sample "
            "(.../fused.zarr/5)."
        ),
    )
    ap.add_argument("--out-bucket", required=True)
    ap.add_argument(
        "--out-prefix",
        required=True,
        help=(
            "Output written to s3://<out-bucket>/<out-prefix>/<source-tile-name>/, "
            "where <source-tile-name> mirrors the input dataset group (e.g. "
            "Tile_X_0002_Y_0006_Z_0000_ch_488.ome.zarr)."
        ),
    )
    ap.add_argument("--aws-region", default="us-west-2")
    ap.add_argument("--devices", nargs="+", default=["cuda:0"])
    ap.add_argument(
        "--workers-per-device",
        type=int,
        default=1,
        help=(
            "GPU workers per device. >1 overlaps the masking function's host-sync "
            "stalls with other workers' compute (raises throughput on this sync-bound "
            "model). Costs ~N x GPU memory."
        ),
    )
    ap.add_argument("--patch", type=int, nargs=3, default=(64, 64, 64))
    ap.add_argument("--block", type=int, nargs=3, default=(256, 256, 256))
    ap.add_argument("--overlap", type=int, default=10)
    ap.add_argument("--batch", type=int, default=8)
    ap.add_argument(
        "--params-json",
        default=None,
        help="Optional JSON file of GfpMaskModel parameters.",
    )
    ap.add_argument("--prep-workers", type=int, default=2)
    ap.add_argument("--writer-workers", type=int, default=2)
    ap.add_argument(
        "--max-inflight-batches",
        type=int,
        default=64,
        help="Max batches queued between stages (queue depth).",
    )
    ap.add_argument(
        "--metrics-json",
        default="gfp_mask_metrics.json",
        help="Where to write pipeline queue/system metrics for bottleneck analysis.",
    )
    ap.add_argument("--metrics-interval", type=float, default=0.5)
    ap.add_argument(
        "--no-pyramid",
        action="store_true",
        help="Write only the segmented level (no coarser levels, no OME metadata).",
    )
    ap.add_argument(
        "--fill-finer-levels",
        action="store_true",
        help="When segmenting a downsampled level L>0, also write the finer levels "
        "(0..L-1) by nearest-upsampling the mask so the pyramid reaches full "
        "resolution (level 0 is a large S3 write; opt-in).",
    )
    ap.add_argument(
        "--pyramid-concurrency",
        type=int,
        default=64,
        help="Max concurrent chunk read+write round-trips in the pyramid build and "
        "upsample passes. These are S3-latency-bound, so raise this (e.g. 128) to go "
        "faster; peak RAM ~ this x chunk^3 x dtype.",
    )
    ap.add_argument(
        "--pyramid-copy-concurrency",
        type=int,
        default=16,
        help="TensorStore data_copy_concurrency for the pyramid passes.",
    )
    ap.add_argument(
        "--pyramid-processes",
        type=int,
        default=1,
        help="Shard the finer-level (--fill-finer-levels) upsample across this many "
        "worker processes to parallelize the S3-latency-bound writes across CPU cores. "
        "Set to your core count (e.g. 8). Total in-flight ~= this x "
        "--pyramid-concurrency, so lower that if you raise this a lot.",
    )
    ap.add_argument(
        "--ccl-block",
        "--hysteresis-block",
        dest="ccl_block",
        type=int,
        default=512,
        help="Block size for the post-hoc connected-components passes (hysteresis and "
        "hole-fill). Larger blocks use more VRAM but less face-stitch memory.",
    )
    ap.add_argument(
        "--ccl-readahead",
        type=int,
        default=8,
        help="Concurrent block reads prefetched during the CCL passes (hysteresis, "
        "hole-fill, instance-labeling) -- they are S3-latency-bound, so higher "
        "overlaps more reads with GPU work. Peak extra RAM ~= this x block^3 x dtype.",
    )
    ap.add_argument(
        "--keep-seed-mask",
        action="store_true",
        help="Keep the intermediate 2-level '_seed' mask after hysteresis (default: "
        "delete it). Useful to re-run hysteresis with a different seed_threshold.",
    )
    ap.add_argument(
        "--fill-holes",
        action="store_true",
        help="Fill enclosed cavities (3D background not reaching the volume border) "
        "in the final binary mask via a seam-correct connected-components pass. Runs "
        "after hysteresis when both are enabled.",
    )
    ap.add_argument(
        "--max-hole-size",
        type=int,
        default=0,
        help="With --fill-holes, only fill cavities of at most this many voxels (0 = "
        "no cap = fill every enclosed cavity, including genuine large lumens).",
    )
    ap.add_argument(
        "--instance-labels",
        action="store_true",
        help="Instead of a binary mask, output an instance-segmentation volume: each "
        "26-connected object gets a unique uint32 ID (seam-correct across blocks). "
        "Runs after hysteresis/hole-fill; the pyramid uses a label-preserving reducer. "
        "Without this flag the output is the usual binary uint8 mask.",
    )
    ap.add_argument(
        "--min-instance-size",
        type=int,
        default=0,
        help="With --instance-labels, drop objects smaller than this many voxels "
        "(set to background). 0 keeps every object.",
    )
    ap.add_argument(
        "--resume-from",
        default=None,
        help="Resume from an existing binary array (a level suffix under the output "
        "group, e.g. '0_fill') instead of recomputing: skips segmentation, hysteresis, "
        "and hole-fill. With --instance-labels, runs only instance-labeling on it -> "
        "{level}/ (+ pyramid). Without --instance-labels it must equal the canonical "
        "level (rebuild the pyramid only).",
    )
    ap.add_argument(
        "--abort-if-blank",
        dest="abort_if_blank",
        action="store_true",
        default=True,
        help="After segmentation, if the mask has no foreground at all, skip "
        "hysteresis/hole-fill/pyramid and exit (nothing to do). On by default.",
    )
    ap.add_argument(
        "--no-abort-if-blank",
        dest="abort_if_blank",
        action="store_false",
        help="Disable the blank check; build the (empty) pyramid even with no "
        "foreground.",
    )
    return ap.parse_args(argv)


def _should_abort_blank(args, base_path: str, seg_level: str) -> bool:
    """True if segmentation is blank and post-processing should be skipped (logs why).

    A blank mask means there is nothing for hysteresis/hole-fill/instances/pyramid to
    do, and building a full pyramid of zeros (esp. --fill-finer-levels to level 0) would
    waste hours of S3 writes.
    """
    if not args.abort_if_blank:
        return False
    if _mask_has_foreground(
        args.out_bucket, base_path, f"{seg_level}/", args.aws_region, args.ccl_block
    ):
        return False
    logger.warning(
        "Segmentation is completely blank (no voxel above threshold in %s%s). "
        "Nothing to post-process; skipping hysteresis/hole-fill/pyramid. Check "
        "threshold/seed_threshold, normalization bounds, and flat-field (and that "
        "--out-prefix is a key, not a full s3:// URL). Pass --no-abort-if-blank to "
        "build the (empty) pyramid anyway.",
        base_path,
        seg_level,
    )
    return True


def _resume_from_binary(
    args,
    base_path,
    level,
    spec,
    start,
    datasets,
    datasets_from_l,
    source_ms,
    omero,
) -> None:
    """Resume from an existing binary: instance-label it (+ pyramid), no recompute.

    Skips segmentation/hysteresis/hole-fill; ``args.resume_from`` is a level suffix
    under the output group (e.g. ``0_fill``). With ``--instance-labels`` it is relabeled
    into ``{level}/`` (uint32); otherwise it must already be the canonical level and
    only the pyramid is rebuilt.
    """
    logger.info(
        "Resume: skipping segmentation/hysteresis/hole-fill; reusing s3://%s/%s%s/",
        args.out_bucket,
        base_path,
        args.resume_from,
    )
    if args.instance_labels:
        _instance_connect(
            args.out_bucket,
            base_path,
            f"{args.resume_from}/",
            f"{level}/",
            args.aws_region,
            block=args.ccl_block,
            min_size=args.min_instance_size,
            readahead=args.ccl_readahead,
        )
    elif args.resume_from.rstrip("/") != level:
        raise SystemExit(
            "--resume-from without --instance-labels must be the canonical level "
            f"'{level}' (pyramid rebuild only); got '{args.resume_from}'."
        )
    if not args.no_pyramid:
        _finalize_pyramid(
            args, base_path, spec, start, datasets, datasets_from_l, source_ms, omero
        )
    logger.info("Done (resume). Output at s3://%s/%s", args.out_bucket, base_path)


def main(argv: Optional[List[str]] = None) -> None:
    """Segment the level encoded in --in-spec and write a matching OME-Zarr pyramid."""
    args = _parse_args(sys.argv[1:] if argv is None else argv)

    # Input spec: explicit --in-spec, else the built-in sample.
    spec = args.in_spec if args.in_spec is not None else DEFAULT_IN_SPEC
    in_bucket, in_kv_path, _ = _kvstore_bucket_path(_load_spec_dict(spec))

    # Level L is the trailing digit of the kvstore path; the group is the path above it.
    in_kv_path = in_kv_path.rstrip("/")
    m = re.search(r"/(\d+)$", in_kv_path)
    if m is None:
        raise ValueError(
            f"The input spec's kvstore path must end with a multiscale level, e.g. "
            f".../fused.zarr/5; got '{in_kv_path}'"
        )
    level = m.group(1)  # keep as the source's path string (e.g. "5")
    group_path = in_kv_path[: m.start()]

    # --- Input store (existing zarr; metadata read from the store) ---
    logger.info("Opening input: s3://%s/%s (level %s)", in_bucket, in_kv_path, level)
    input_store = open_ts_spec(spec)
    shape = tuple(input_store.domain.shape)
    logger.info("Input shape=%s dtype=%s", shape, input_store.dtype)
    if len(shape) != 5:
        raise ValueError(
            f"Expected a 5D (T, C, Z, Y, X) input store, got shape {shape}."
        )
    z, y, x = shape[2:]

    # --- Source multiscales metadata (for pyramid + OME output) ---
    source_ms = datasets = omero = None
    datasets_from_l: list = []
    start = 0
    if not args.no_pyramid:
        ms_info = _read_source_multiscales(in_bucket, group_path)
        if ms_info is None:
            raise ValueError(
                "No OME multiscales metadata found on the source group; rerun with "
                "--no-pyramid to write only the segmented level."
            )
        source_ms, datasets, omero = ms_info
        paths = [d.get("path") for d in datasets]
        if level not in paths:
            raise ValueError(f"Level '{level}' not among source datasets {paths}.")
        start = paths.index(level)
        datasets_from_l = datasets[start:]

    # Clamp patch/block to the (possibly small) downsampled volume.
    patch = tuple(min(p, d) for p, d in zip(args.patch, (z, y, x)))
    block = tuple(min(b, d) for b, d in zip(args.block, (z, y, x)))
    if patch != tuple(args.patch) or block != tuple(args.block):
        logger.info(
            "Clamped to (Z,Y,X)=(%d,%d,%d): patch=%s block=%s", z, y, x, patch, block
        )

    # --- Output: segmented level written at the source's level index ---
    # Mirror the source dataset/tile name (the ".ome.zarr"/".zarr" group), e.g.
    # ".../Tile_X_0002_Y_0006_Z_0000_ch_488.ome.zarr/0" -> the output group is
    # "<out-prefix>/Tile_X_0002_Y_0006_Z_0000_ch_488.ome.zarr/".
    tile_name = group_path.rstrip("/").rsplit("/", 1)[-1]
    base_path = f"{args.out_prefix.rstrip('/')}/{tile_name}/"

    # --- Resume: reuse an existing binary; skip segmentation/hysteresis/hole-fill ---
    if args.resume_from:
        _resume_from_binary(
            args,
            base_path,
            level,
            spec,
            start,
            datasets,
            datasets_from_l,
            source_ms,
            omero,
        )
        return

    # Hysteresis (dual-threshold) is enabled when params.json sets seed_threshold. The
    # streaming pass then writes a 2-level mask {0,1,2} to an intermediate "_seed" path;
    # a seam-correct connected-components pass collapses it to the final binary level.
    seed_thr = _seed_threshold(args.params_json, _model_threshold(args.params_json))
    hysteresis = seed_thr is not None
    stages = _mask_stages(level, hysteresis, args.fill_holes, args.instance_labels)
    seg_level = dict(stages)["seg"]
    seg_path = f"{base_path}{seg_level}/"
    chunks = (1, 1, min(128, z), min(128, y), min(128, x))
    logger.info(
        "Creating %s level: s3://%s/%s",
        "intermediate 2-level" if hysteresis else "segmented",
        args.out_bucket,
        seg_path,
    )
    output_store = _open_or_create_s3_mask_zarr(
        args.out_bucket, seg_path, (1, 1, z, y, x), chunks, args.aws_region
    )

    # --- Model + config ---
    model = load_model("gfp-mask", args.params_json)
    # One GpuWorker is created per device entry, so repeating each device runs
    # multiple workers on it (hides the masking function's host-sync stalls).
    devices = args.devices * max(1, args.workers_per_device)
    logger.info("GPU workers: %s", devices)

    # Normalization comes from the same --params-json (see _normalization_kwargs).
    norm_kwargs = _normalization_kwargs(args.params_json)
    logger.info("Normalization: %s", norm_kwargs)

    cfg = InferenceConfig(
        patch=patch,
        block=block,
        overlap=args.overlap,
        batch_size=args.batch,
        devices=devices,
        max_inflight_batches=args.max_inflight_batches,
        amp=False,  # no torch math in the model; avoid a pointless float16 copy
        use_compile=False,  # torch.compile cannot trace the cupy/cuCIM region
        output_denormalize=False,  # mask is not in intensity space
        seam_mode="trim",
        **norm_kwargs,  # normalize / norm_lower / norm_upper from --params-json
    )
    logger.info("Inference config:\n%s", cfg)

    # Optional flat-field background (estimated once at the processing resolution).
    background = _estimate_background(spec, cfg, (z, y, x))

    run(
        model,
        input_store,
        output_store,
        cfg,
        metrics_json=args.metrics_json,
        metrics_interval=args.metrics_interval,
        num_prep_workers=max(1, args.prep_workers),
        num_writer_workers=max(1, args.writer_workers),
        background=background,
    )
    _summarize_metrics(args.metrics_json)

    # Bail out early if the segmentation is completely blank: no foreground means there
    # is nothing for hysteresis/hole-fill/pyramid to do, and building a full pyramid of
    # zeros (esp. --fill-finer-levels to level 0) would waste hours of S3 writes.
    if _should_abort_blank(args, base_path, seg_level):
        return

    # --- Post-processing: hysteresis / hole-fill / instance labels -> {level}/ ---
    # No-op when there are no post-seg stages (plain binary: seg wrote {level}/ itself).
    _run_postprocess(args, base_path, stages)

    if args.no_pyramid:
        logger.info(
            "Done (single level %s). Skipped pyramid + OME metadata (--no-pyramid).",
            level,
        )
        return

    _finalize_pyramid(
        args, base_path, spec, start, datasets, datasets_from_l, source_ms, omero
    )
    logger.info("Done. OME-Zarr mask written to s3://%s/%s", args.out_bucket, base_path)


if __name__ == "__main__":
    main()
